server:
  port: 80

mybatis:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: io.github.aicyi.midware.db.commons.ibatis.IbatisLogger

spring:
  profiles:
    active: test
  application:
    name: aicyi-example-consumer
  #    datasource:
  #    dynamic:
  #      druid:
  #        initial-size: 5
  #        min-idle: 5
  #        max-wait: 60000
  #        max-active: 20
  #        min-evictable-idle-time-millis: 300000
  #        time-between-eviction-runs-millis: 60000
  #        validation-query: SELECT 1 FROM DUAL
  #        init-connection-sqls: SET NAMES utf8mb4
  #        # 下面这两个配置，可以在每次连接的时候判断一些连接是否有效
  #        test-on-borrow: true
  #        test-while-idle: true

  # redis配置
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  cloud:
    stream:
      # 绑定配置
      bindings:
        message-input:
          destination: default.exchange
          group: default.queue
          content-type: application/json
          binder: rabbit
          consumer:
            concurrency: 3 # 最大并发数
            max-attempts: 3 # 最大重试次数
            back-off-initial-interval: 1000 # 重试间隔(ms)

        delayed-input:
          destination: delayed.exchange
          group: delayed.queue
          content-type: application/json
          binder: rabbit

        direct-input:
          destination: direct.exchange
          group: direct.queue
          binder: rabbit

        orderEvents-in-0:
          destination: topic.exchange
          group: order-service
          binder: rabbit

        systemLogs-in-0:
          destination: topic.exchange
          group: log-service
          binder: rabbit

      # RabbitMQ特定配置
      rabbit:
        bindings:
          message-input:
            consumer:
              queue-name-group-only: true # 队名列等于组名，默认队列名等于交换机+组名
              durable-subscription: true # 持久化订阅
              exchange-auto-delete: false # 不自动删除交换机
              declare-exchange: false # 不自动声明交换机
              bind-queue: false # 不自动绑定队列

          delayed-input:
            consumer:
              queue-name-group-only: true
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          direct-input:
            consumer:
              queue-name-group-only: true
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          orderEvents-in-0:
            consumer:
              durable-subscription: true
              declare-exchange: false
              bind-queue: false

          systemLogs-in-0:
            consumer:
              durable-subscription: true
              declare-exchange: false
              bind-queue: false