<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.aicyi.example</groupId>
    <artifactId>aicyi-example</artifactId>

    <packaging>pom</packaging>
    <name>aicyi example</name>
    <description>aicyi example</description>

    <parent>
        <groupId>io.github.aicyi.base</groupId>
        <artifactId>aicyi-base-starter-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <modules>
        <module>aicyi-example-boot</module>
        <module>aicyi-example-dao</module>
        <module>aicyi-example-domain</module>
        <module>aicyi-example-fixture</module>
        <module>aicyi-example-mybatisplus</module>
        <module>aicyi-example-rabbitmq</module>
        <module>aicyi-example-service</module>
        <module>aicyi-example-test</module>
        <module>aicyi-example-web</module>
        <module>aicyi-example-xxljob</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- Spring Boot Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.aicyi.commons</groupId>
                <artifactId>aicyi-commons</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.midware</groupId>
                <artifactId>aicyi-midware</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-boot</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-rabbitmq</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-dao</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-domain</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-fixture</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-mybatisplus</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-service</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-test</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.github.aicyi.example</groupId>
                <artifactId>aicyi-example-web</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>