<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>aicyi-example-service</artifactId>

    <packaging>jar</packaging>
    <name>aicyi example service</name>
    <description>aicyi example service</description>

    <parent>
        <groupId>io.github.aicyi.example</groupId>
        <artifactId>aicyi-example</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>io.github.aicyi.example</groupId>
            <artifactId>aicyi-example-dao</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-message-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-kit</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-message-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-message-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-rabbitmq</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.aicyi.midware</groupId>
            <artifactId>aicyi-midware-redis</artifactId>
        </dependency>
    </dependencies>
</project>