# Nacos dataId: aicyi-example.yml
# group: DEFAULT_GROUP，格式：YAML
# 共享配置（所有环境生效），当前无环境无关的公共配置项，可按需扩展

mybatis:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: io.github.aicyi.midware.db.commons.ibatis.IbatisLogger
    
spring:
  mvc:
  path-match:
    matching-strategy: ant_path_matcher
    
  freemarker:
    check-template-location: false