# Nacos dataId: aicyi-example.yml
# group: DEFAULT_GROUP，格式：YAML
# 共享配置（所有环境生效）

mybatis:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: io.github.aicyi.midware.db.commons.ibatis.IbatisLogger

spring:
  freemarker:
    check-template-location: false
