# Nacos dataId: aicyi-rabbitmq.yml
# group: DEFAULT_GROUP，格式：YAML
# RabbitMQ 环境配置（由 application-test.yml 迁移拆分而来，需导入到各环境对应的 namespace）

spring:
  cloud:
    stream:
      # 默认绑定器配置
      default-binder: rabbit

      # 绑定器配置
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: test
                password: test
                virtual-host: /

  # RabbitMQ原生配置
  rabbitmq:
    dynamic: false
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          stateless: true